#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.properties.hibernate.default_schema=PMS_db
#spring.datasource.tomcat.max-wait=20000
#spring.datasource.tomcat.max-active=50

#spring.datasource.tomcat.max-idle=20
#spring.datasource.tomcat.min-idle=15

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.id.new_generator_mappings = false
spring.jpa.properties.hibernate.format_sql = true

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.sql.init.mode=always

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

server.port=9090

jwt.secret=SecretKey1234
jwt.expiration=3600000  # 1 hour

# Set the root logging level (applies to all packages)
logging.level.root=INFO

# Log pattern for console
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n

# Log pattern for file
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

spring.security.user.name=admin
spring.security.user.password=admin123




